version: '3'
services:
  web:
    build: .
    ports:
      - "3000:3000"
    links:
      - neo4j
  neo4j:
    image: "neo4j"
    ports: 
      - 7474:7474 
      - 7687:7687
    environment: 
      - NEO4J_AUTH=none
    volumes:
      - $PWD/import:/var/lib/neo4j/import
      - $PWD/data:/data
      - $PWD/logs:/logs